apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
        - name: cloudflared
          image: chad0/tunnel:new
          imagePullPolicy: Always
