apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-stream
  template:
    metadata:
      labels:
        app: price-stream
    spec:
      containers:
        - name: price-stream
          image: "{{ .Values.image.repository}}::{{ .Values.image.tag}}"
          command: ["node","index.js"]
          ports:
            - containerPort: 4003
          env:
            - name: REDIS_HOST
              value: "redis"

---

apiVersion: v1
kind: Service
metadata:
  name: price-stream
spec:
  type: ClusterIP
  selector:
    app: price-stream
  ports:
    - port: 4003
      targetPort: 4003
