apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exchange-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: yourdomain.com
      http:
        paths:
          - path: /orders(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 4002
          - path: /price(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: price-stream
                port:
                  number: 4003
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000
