apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-engine
  template:
    metadata:
      labels:
        app: matching-engine
    spec:
      containers:
        - name: matching-engine
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
          env:
            - name: REDIS_HOST
              value: "redis"  
        