apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: chad0/order-service:new
          command: ["node","index.js"]
          ports:
            - containerPort: 4002
          env:
            - name: REDIS_HOST
              value: "redis"

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - port: 4002
      targetPort: 4002
