name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'candles/**'
      - 'matching-engine/**'
      - 'price-stream/**'
      - 'orders/**'
      - 'services/order-service/**'
      - 'helm/**'
      - 'redis/**'
      - 'api-gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-gateway, candles, matching-engine, price-stream, services/order-service]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set image name
        id: vars
        run: |
          IMAGE_NAME=$(basename ${{ matrix.service }})
          echo "imagename=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ steps.vars.outputs.imagename }}:${{ github.sha }}

  update-and-deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y yq
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Pull latest main
        run: |
          git fetch origin main
          git checkout main
          git pull --rebase origin main

      - name: Update Helm values.yaml for all charts
        run: |
          IMAGE_TAG=${{ github.sha }}
          CHARTS=("candles" "matching-engine" "price-stream" "orders" "redis" "api-gateway")

          for chart in "${CHARTS[@]}"; do
            VALUES_FILE="helm/$chart/values.yaml"
            if [ -f "$VALUES_FILE" ]; then
              echo "Setting tag to $IMAGE_TAG in $VALUES_FILE"
              yq -i -y ".image.tag = \"$IMAGE_TAG\"" "$VALUES_FILE"
              git add "$VALUES_FILE"
            else
              echo "No values.yaml for $chart, skipping"
            fi
          done

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "ci: update all Helm charts to $IMAGE_TAG"
            git push origin main
          fi

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes using Helm
        run: |
          CHARTS=("candles" "matching-engine" "price-stream" "orders" "redis" "api-gateway")
          for chart in "${CHARTS[@]}"; do
            echo "Deploying chart: $chart"
            helm upgrade --install $chart ./helm/$chart --namespace default --create-namespace
          done
