name: CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'candles/**'
      - 'matching-engine/**'
      - 'price-stream/**'
      - 'services/order-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [candles, matching-engine, price-stream, services/order-service]
  

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: set image name
        id: vars
        run: |
          IMAGE_NAME=$(basename ${{ matrix.service }})
          echo "imagename=$IMAGE_NAME" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ matrix.service }}:latest
